name: Node Continuous Integration
on:
  pull_request:
    branches: [ main ]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
         issue-close-message: "@${issue.user.login} this issue was automatically closed because it matched a spam regex"
         issue-pattern: '^[MXDIGIWAL-\d*] - '
      - run: npm install -g bats
      - run: bats -v
      






